[project]
name = "comfyui-standard-trigger-words"
description = "Updated Icon Image for node registry"
version = "2.1.3"
license = {text = "MIT"}
dependencies = []

[project.urls]
Repository = "https://github.com/revisionhiep-create/comfyui-standard-trigger-words"

[tool.comfy]
PublisherId = "revybevy"
DisplayName = "Standard Trigger Words ğŸ“"
Icon = "https://raw.githubusercontent.com/revisionhiep-create/comfyui-standard-trigger-words/refs/heads/main/Node%20Icon.png"
