[project]
name = "comfyui-standard-trigger-words"
description = "Added remove and edit category in the UI"
version = "2.1.1"
license = {text = "MIT"}
dependencies = []

[project.urls]
Repository = "https://github.com/revisionhiep-create/comfyui-standard-trigger-words"

[tool.comfy]
PublisherId = "revybevy"
DisplayName = "Standard Trigger Words ğŸ“"
Icon = "https://raw.githubusercontent.com/revisionhiep-create/comfyui-standard-trigger-words/refs/heads/main/Infograph.png"
