[project]
name = "comfyui-standard-trigger-words"
description = "Interactive button-based trigger word manager with precision weighting and portable collections."
version = "2.4.4"
license = {text = "MIT"}
dependencies = []

[project.urls]
Repository = "https://github.com/revisionhiep-create/comfyui-standard-trigger-words"

[tool.comfy]
PublisherId = "revybevy"
DisplayName = "Standard Trigger Words ğŸ“"
Icon = "https://raw.githubusercontent.com/revisionhiep-create/comfyui-standard-trigger-words/refs/heads/main/Node%20Icon.png"
